// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfdbtsdicyrlmbuoplye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZGJ0c2RpY3lybG1idW9wbHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjU4OTgsImV4cCI6MjA1ODk0MTg5OH0.vnSnQaKj-cQjBN5iLFY4342HEM7Vr0koYW0glXJhAts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);